# Linear Algebra - Fundamental Concepts

Linear algebra is a branch of mathematics that is widely used throughout science and engineering. However, because linear algebra is a form of continuous rather than discrete mathematics, many computer scientists have little experience with it. A good understanding of linear algebra is essential for understanding and working with many machine learning algorithms, especially deep learning algorithms. We therefore precede our introduction to deep learning with a focused presentation of the key linear algebra prerequisites.

The theoretical summary of all content is available at: [chapter-02-notes.pdf](chapter-02-notes.pdf).

## Importing Python's Numpy Package

In [1]:
import numpy as np

### Scalars, Vectors, Matrices and Tensors

In [2]:
scalar = np.array(42)
print(f'Scalar:\n{scalar}')

Scalar:
42


In [3]:
vector = np.array([1, 2, 3])
print(f'Vector:\n{vector}')

Vector:
[1 2 3]


In [4]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(f'Tensor:\n{tensor}')

Tensor:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


## Transpose of the Matrix

In [6]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(f'Original Matrix:\n{matrix}')

transpose_matrix = np.transpose(matrix)
print(f'\nTranspose of The Matrix:\n{transpose_matrix}')

print(f'\nTranspose of The Matrix (Another Way):\n{matrix.T}')

Original Matrix:
[[1 2]
 [3 4]
 [5 6]]

Transpose of The Matrix:
[[1 3 5]
 [2 4 6]]

Transpose of The Matrix (Another Way):
[[1 3 5]
 [2 4 6]]


## Multiplying Matrices and Vectors

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

In [10]:
print(f'Matrix A:\n{A}')
print(f'\nMatrix B:\n{B}')

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]


In [9]:
C = np.dot(A, B)

print(f'A x B:\n{C}')

A x B:
[[ 58  64]
 [139 154]]


### Element-wise Product (Hadamard product)

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

In [12]:
C = np.multiply(A, B)

print(f'Element Wise Product A * B =\n{C}')

Element Wise Product A * B =
[[ 7 16 27]
 [40 55 72]]


## Identity and Inverse Matrices

In [13]:
I = np.eye(3)

print(f'Identity Matrix:\n{I}')

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print(f'Inverse of Matrix A:\n{A_inv}')

I = np.dot(A, A_inv)
print(f'\nA x A^-1 =\n{np.round(I, 2)}')

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A x A^-1 =
[[1. 0.]
 [0. 1.]]


## Linear Dependence

In [94]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Linearly Dependent Matrix:\n{A}')

A_linear_combination = -1 * np.array([1, 2, 3]) + 2 * np.array([4, 5, 6]) - 1 * np.array([7, 8, 9])

assert (A_linear_combination == np.array([0, 0, 0])).all()

Linearly Dependent Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Norms

In [70]:
v = np.array([1, 2, -3, 0, 4, -5])

print(f'L0 Norm: {np.count_nonzero(v)}')
print(f'L1 Norm: {np.linalg.norm(v, ord = 1)}')
print(f'L2 Norm: {np.linalg.norm(v, ord = 2)}')
print(f'Max Norm: {np.linalg.norm(v, ord = np.inf)}')

L0 Norm: 5
L1 Norm: 15.0
L2 Norm: 7.416198487095663
Max Norm: 5.0


## Special Kinds of Matrices and Vectors

### Diagonal matrices

In [71]:
v = np.array([1, 2, 3])
D = np.diag(v)

print(f'Diagonal Matrix:\n{D}')

Diagonal Matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Symmetric Matrix

In [77]:
v = np.array([1, 2, 3, 4, 5, 6])

A = np.zeros((3, 3))
A[np.triu_indices(3)] = v
A = A + A.T - np.diag(A.diagonal())

print(f'Symmetric Matrix:\n{A}')

Symmetric Matrix:
[[1. 2. 3.]
 [2. 4. 5.]
 [3. 5. 6.]]


### Unit Vector

In [80]:
v = np.array([3, 4, 5])

length = np.sqrt(np.sum(v**2))
unit_v = v / length

print(f'Vector v = {v} with length = {length}')
print(f'Unit Vector of v = {unit_v} with length = {np.round(np.sqrt(np.sum(unit_v**2)), 2)}')


Vector v = [3 4 5] with length = 7.0710678118654755
Unit Vector of v = [0.42426407 0.56568542 0.70710678] with length = 1.0


### Orthogonal Matrix

In [93]:
A = np.random.rand(3, 3)

Q, R = np.linalg.qr(A)

print(f'Original Matrix:\n{A}')
print(f'\nOrthogonal Matrix:\n{Q}')

assert (np.eye(3) == np.round(np.dot(Q.T, Q), 2)).all()

Original Matrix:
[[0.63353088 0.68335045 0.31662868]
 [0.50817784 0.07903943 0.03618055]
 [0.10966345 0.50553096 0.81202509]]

Orthogonal Matrix:
[[-0.77304014  0.33039905 -0.54152138]
 [-0.62008322 -0.57364225  0.53519284]
 [-0.13381234  0.74951387  0.64832339]]


## Eigendecomposition

In [92]:
A = np.random.rand(3, 3)

eigenvalues, eigenvectors = np.linalg.eig(A)

print('Original Matrix:\n{A}')
print(f'\nEigen Values:\n{eigenvalues}')
print(f'\nEigen Vectors:\n{eigenvectors}')

assert (np.round(np.dot(A, eigenvectors), 2) == np.round(np.dot(eigenvectors, np.diag(eigenvalues)), 2)).all()

Original Matrix:
{A}

Eigen Values:
[ 1.99369247 -0.23422298 -0.32669518]

Eigen Vectors:
[[-0.52203254 -0.15513372  0.11510005]
 [-0.56070003 -0.74068    -0.8280084 ]
 [-0.64272661  0.65370227  0.54877507]]


## Singular Value Decomposition

In [119]:
A = np.random.rand(3, 5)

U, S, Vt = np.linalg.svd(A)

Sigma = np.zeros((3, 5))
Sigma[:3, :3] = np.diag(S)

print(f'Original Matrix:\n{A}')
print(f'\nU Matrix:\n{U}')
print(f'\nS Matrix:\n{S}')
print(f'\nV Transpose Matrix:\n{Vt}')

assert (np.round(A, 2) == np.round(np.dot(U, np.dot(Sigma, Vt)), 2)).all()

Original Matrix:
[[0.62171697 0.48429006 0.63997956 0.34123429 0.33443013]
 [0.99530156 0.75694761 0.85936708 0.85421092 0.54446677]
 [0.32372046 0.00582868 0.96514488 0.49747079 0.17645895]]

U Matrix:
[[-0.47208276  0.16946761  0.8651119 ]
 [-0.77056611  0.39736081 -0.49832948]
 [-0.42821227 -0.90187866 -0.05700119]]

S Matrix:
[2.34327508 0.61535005 0.18030191]

V Transpose Matrix:
[[-0.51170628 -0.34754736 -0.58789911 -0.4405543  -0.27866478]
 [ 0.33947856  0.61362801 -0.68336545 -0.08352999  0.18506584]
 [ 0.12986104  0.22974548  0.39040952 -0.88090612  0.04402214]
 [-0.69624606  0.65926466  0.18507196  0.14329217 -0.16070862]
 [-0.34826502 -0.12352578 -0.0267408  -0.04905527  0.92754049]]
